steps:
  # Gradnja Docker slike
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=MONGO_DATABASE=$_MONGODB'
      - '--build-arg=MONGO_USER=$_MONGO_USER'
      - '--build-arg=MONGO_PASSWORD=$_MONGO_PASSWORD'
      - '--build-arg=MONGO_CLUSTER=$_MONGO_CLUSTER'
      - '-t'
      - 'gcr.io/techtitans-407214/gcptest'
      - '.'

# ... ostatak cloudbuild.yaml

